version: "3.8"

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    # Команда запускается та, что в Dockerfile (gunicorn ...)

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    # Для Celery-воркера нужно переопределить CMD, 
    # чтобы вместо gunicorn запускался Celery:
    command: >
      celery -A app.tasks worker --loglevel=INFO
    depends_on:
      - flask_app
    environment:
      - FLASK_ENV=development
