services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile  # Укажите путь к вашему Flask Dockerfile
    container_name: flask_app
    env_file:
      - .env
    volumes:
      - app_data:/app/convertorData
    networks:
      - traefik_network
      - app_network
    labels:
      - traefik.enable=true

      # Роутер: принимает только те запросы, что приходят на intplab.com и путь начинается с /api
      - traefik.http.routers.flask.rule=Host(`intplab.com`) && PathPrefix(`/api`)

      # Пробрасываем на HTTPS (websecure) с сертификатом
      - traefik.http.routers.flask.entrypoints=websecure
      - traefik.http.routers.flask.tls=true
      - traefik.http.routers.flask.tls.certresolver=mytlschallenge
      - traefik.docker.network=traefik_network
 
      # Настраиваем сервис: контейнер слушает порт 5000 (Gunicorn/Flask)
      - traefik.http.services.flask.loadbalancer.server.port=5000

      #   (Дополнительно) StripPrefix, если хотите, чтобы во Flask маршруты оставались "/youtube/search_channel"
      # а не "/api/youtube/search_channel".
      # Иначе, без этой настройки, Flask будет видеть путь как "/api/youtube/search_channel".
      - traefik.http.middlewares.flask-strip.stripPrefix.prefixes=/api
      - traefik.http.routers.flask.middlewares=flask-strip
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile  # Укажите путь к вашему Celery Dockerfile
    container_name: celery_worker
    command: >
      celery -A tasks worker --loglevel=INFO
    depends_on:
      - flask_app
    env_file:
      - .env
    volumes:
      - app_data:/app/convertorData
    networks:
      - traefik_network
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`intplab.com`, `www.intplab.com`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=mytlschallenge
      - traefik.http.services.frontend.loadbalancer.server.port=5000  # Порт, на котором работает serve внутри контейнера
    networks:
      - traefik_network
      - app_network

networks:
  traefik_network:
    external: true
  app_network:
    driver: bridge

volumes:
  app_data: