services:
  # n8n Service
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - N8N_HOST=n8n.intplab.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.intplab.com/
      - GENERIC_TIMEZONE=America/Los_Angeles
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app_network
    ports:
      - "8000:5678"  # Expose n8n on host port 8000

  # Flask App (API)
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    env_file:
      - .env
    volumes:
      - ./app/convertorData:/app/convertorData  
    networks:
      - app_network
    ports:
      - "5500:5000"  # Expose Flask app on host port 5500
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - app_network
    ports:
      - "9000:5000"  # Expose frontend on host port 9000
  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: >
      celery -A tasks worker --loglevel=INFO
    depends_on:
      - flask_app
    env_file:
      - .env
    volumes:
      - ./app/convertorData:/app/convertorData 
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  n8n_data:
  app_data:

