version: "3.8"

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - app_data:/app/convertorData

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: >
      celery -A tasks worker --loglevel=INFO
    depends_on:
      - flask_app
    env_file:
      - .env
    volumes:
      - app_data:/app/convertorData
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - flask_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app_data: