"""Add DownloadFragment

Revision ID: 20f630ab953a
Revises: 3632fd49bebf
Create Date: 2025-01-31 04:42:26.956887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20f630ab953a'
down_revision: Union[str, None] = '3632fd49bebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_fragments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('fragment_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_dictionary_words')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('user_dictionary_words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('word', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('translation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('definition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('example', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_review_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repetition_stage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ease_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_dictionary_words_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_dictionary_words_pkey')
    )
    op.drop_table('download_fragments')
    # ### end Alembic commands ###
