"""Add status to Transcript

Revision ID: 33fab1a870f6
Revises: 6a84cdfdb121
Create Date: 2025-01-19 23:13:06.588693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fab1a870f6'
down_revision: Union[str, None] = '6a84cdfdb121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'status')
    # ### end Alembic commands ###
