"""Refactor transcripts schema

Revision ID: 3632fd49bebf
Revises: e108c66be6a7
Create Date: 2025-01-22 19:44:00.034596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3632fd49bebf'
down_revision: Union[str, None] = 'e108c66be6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('dimension', sa.String(length=50), nullable=True),
    sa.Column('definition', sa.String(length=50), nullable=True),
    sa.Column('caption', sa.Boolean(), nullable=True),
    sa.Column('licensed_content', sa.Boolean(), nullable=True),
    sa.Column('projection', sa.String(length=50), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('dislike_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('privacy_status', sa.String(length=50), nullable=True),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('embeddable', sa.Boolean(), nullable=True),
    sa.Column('public_stats_viewable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transcription_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['transcripts.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_transcript',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['transcripts.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_transcript')
    op.drop_table('transcription_words')
    op.drop_table('users')
    op.drop_table('transcripts')
    # ### end Alembic commands ###
