"""Add users table

Revision ID: 56d9689eb628
Revises: e0f47c7502bb
Create Date: 2025-01-21 23:34:29.704287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d9689eb628'
down_revision: Union[str, None] = 'e0f47c7502bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('transcripts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transcripts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.drop_column('transcripts', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
