"""Use video_id as primary key in Transcript

Revision ID: ad4db6708c51
Revises: 
Create Date: 2025-01-19 02:19:03.759237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4db6708c51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('transcription_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['transcripts.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcription_words')
    op.drop_table('transcripts')
    # ### end Alembic commands ###
