"""Add error to Transcript

Revision ID: e0f47c7502bb
Revises: 33fab1a870f6
Create Date: 2025-01-20 17:23:12.390403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f47c7502bb'
down_revision: Union[str, None] = '33fab1a870f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('error', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'error')
    # ### end Alembic commands ###
