"""Added new columns to Transcript 

Revision ID: e108c66be6a7
Revises: d029248482c0
Create Date: 2025-01-22 18:13:49.104777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e108c66be6a7'
down_revision: Union[str, None] = 'd029248482c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('transcripts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('transcripts', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('transcripts', sa.Column('channel_id', sa.String(length=255), nullable=True))
    op.add_column('transcripts', sa.Column('channel_title', sa.String(length=255), nullable=True))
    op.add_column('transcripts', sa.Column('category_id', sa.String(length=50), nullable=True))
    op.add_column('transcripts', sa.Column('thumbnail_url', sa.String(length=512), nullable=True))
    op.add_column('transcripts', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('transcripts', sa.Column('duration', sa.String(length=50), nullable=True))
    op.add_column('transcripts', sa.Column('dimension', sa.String(length=50), nullable=True))
    op.add_column('transcripts', sa.Column('definition', sa.String(length=50), nullable=True))
    op.add_column('transcripts', sa.Column('caption', sa.Boolean(), nullable=True))
    op.add_column('transcripts', sa.Column('licensed_content', sa.Boolean(), nullable=True))
    op.add_column('transcripts', sa.Column('projection', sa.String(length=50), nullable=True))
    op.add_column('transcripts', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('transcripts', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('transcripts', sa.Column('dislike_count', sa.Integer(), nullable=True))
    op.add_column('transcripts', sa.Column('favorite_count', sa.Integer(), nullable=True))
    op.add_column('transcripts', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('transcripts', sa.Column('privacy_status', sa.String(length=50), nullable=True))
    op.add_column('transcripts', sa.Column('license', sa.String(length=50), nullable=True))
    op.add_column('transcripts', sa.Column('embeddable', sa.Boolean(), nullable=True))
    op.add_column('transcripts', sa.Column('public_stats_viewable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'public_stats_viewable')
    op.drop_column('transcripts', 'embeddable')
    op.drop_column('transcripts', 'license')
    op.drop_column('transcripts', 'privacy_status')
    op.drop_column('transcripts', 'comment_count')
    op.drop_column('transcripts', 'favorite_count')
    op.drop_column('transcripts', 'dislike_count')
    op.drop_column('transcripts', 'like_count')
    op.drop_column('transcripts', 'view_count')
    op.drop_column('transcripts', 'projection')
    op.drop_column('transcripts', 'licensed_content')
    op.drop_column('transcripts', 'caption')
    op.drop_column('transcripts', 'definition')
    op.drop_column('transcripts', 'dimension')
    op.drop_column('transcripts', 'duration')
    op.drop_column('transcripts', 'tags')
    op.drop_column('transcripts', 'thumbnail_url')
    op.drop_column('transcripts', 'category_id')
    op.drop_column('transcripts', 'channel_title')
    op.drop_column('transcripts', 'channel_id')
    op.drop_column('transcripts', 'published_at')
    op.drop_column('transcripts', 'description')
    op.drop_column('transcripts', 'title')
    # ### end Alembic commands ###
